### ISSUE TITLE
Parallel calls or chained in series?

### ISSUE THREAD

**Issue by AussieFlem** [s9tpepper/MongoAS3#11]
I'm finding if I have a method with two calls:

eg:
private function initApplication():void
{
     mongo.db("myDatabase").collection("myCollection").find(query, findOptions).add(onCursorReady);
     mongo.db("myDatabase").collection("myOtherCollection").find(query, findOptions).add(onOtherCursorReady);
}

Neither of the handlers seem to fire.
If I call the first find(), and the second from the handler of the first, it works fine - handlers fire and data gets returned and used.

Am I doing something stupid, or is this the way it's supposed to work?
I would have thought the asynchronous approach with listeners would have meant I could throw off a whole bunch of operations and they'd sort themselves out via the handlers

Any help appreciated :)

**Comment by s9tpepper** [comment]
Yea this is definitely an issue, I'll have to write up some tests and see where there's something going wrong here. I hadn't noticed this as I usually use the Task framework from the spicelib guys (http://www.spicefactory.org/parsley/docs/2.3/manual/task.php) just cause I've been using it for so long before I even started using MongoDB.

**Comment by AussieFlem** [comment]
Cheers - will check it out.

**Comment by AussieFlem** [comment]
Looks like @ericsoco has taken care of this one in Issue #12 - I'll close this one off :)
