### ISSUE TITLE
failed to mutiple query

### ISSUE THREAD

**Issue by bat007** [s9tpepper/MongoAS3#8]
Hi manito,
I tried to implement your lib.
Mostly it works but when i tried to run multiple findOne () it block.
codes similar to 
for(var i:int=0;i<10;i++)
{
_mongo.db(_database).collection(_collection).find(query1,findOptions);
}
or i run the some queries continuously

Neither worked.

So it only work in serial but in concurrent ?

Regards,
Bat

**Comment by s9tpepper** [comment]
There is no concurrency in Flash, at least not yet until they release the Workers API, so currently the driver is limited to the capabilities of the Socket class. 

I recommend not executing queries in such a manner and use an asynchronous task manager to manage multiple sequential querites. I use the spicelib Task framework from the Parsley library: http://www.spicefactory.org/parsley/docs/2.0/manual/task.php

Hope that helps,

-omar

**Comment by bat007** [comment]
ok
Thank you very much for your help!
